import enum

class ReviewStatus(enum.StrEnum):
    """
    Statuses for feedback

    Attributes:
        DRAFT: The feedback is still being developed by the author, and is not ready to be seen by others
        PILOT: The feedback is authored, but is not yet ready to be seen by students (only other reviewers)
        PUBLISHED: The feedback is authored and ready to be seen by students
        PRIVATE: The feedback is complete, but is not visible to students. It is exclusively meant for other reviewers.
        DELETED: The feedback has been deleted and is no longer visible to anyone (but can be retrieved)
    """
    DRAFT = "draft"
    PILOT = "pilot"
    PUBLISHED = "published"
    PRIVATE = "private"
    DELETED = "deleted"


class ReviewCommentFormat(enum.StrEnum):
    """
    Formats for feedback comments

    Attributes:
        MARKDOWN: The feedback is written in Markdown format
        HTML: The feedback is written in HTML format
        TEXT: The feedback is written in plain text format
    """
    MARKDOWN = "markdown"
    HTML = "html"
    TEXT = "text"


class ReviewTools(enum.StrEnum):
    """
    Tools that can generate feedback

    Attributes:
        OVERRIDE: Feedback generated by an instructor applying a grade override
        MANUAL: Feedback generated by a human using the review tool
        PEDAL: Feedback generated by Pedal
        QUIZ: Feedback generated by a quiz
    """
    OVERRIDE = "override"
    MANUAL = "manual"
    PEDAL = "pedal"
    QUIZ = "quiz"