"""empty message

Revision ID: 779576d3703b
Revises: 
Create Date: 2019-07-14 13:30:45.813112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '779576d3703b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('submission_index', 'submission', ['assignment_id', 'course_id', 'user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('submission_index', table_name='submission')
    # ### end Alembic commands ###
