"""prism_update

Revision ID: 981662a4cab3
Revises: a62e70d564b3
Create Date: 2025-05-24 00:40:04.295478

"""
import sqlalchemy_utc
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '981662a4cab3'
down_revision = 'a62e70d564b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_log',
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('route', sa.String(length=255), nullable=False),
    sa.Column('method', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=255), nullable=False),
    sa.Column('client_timestamp', sa.String(length=255), nullable=True),
    sa.Column('client_timezone', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('date_modified', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('access_log', schema=None) as batch_op:
        batch_op.create_index('access_log_subject_index', ['subject_id'], unique=False)

    op.create_table('course_log',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('CREATE', 'DELETE', 'TRANSFER', 'RENAME', 'EDIT', 'ARCHIVE', 'CORRUPTED', name='courselogevent'), nullable=False),
    sa.Column('field', sa.String(length=255), nullable=True),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('client_timestamp', sa.String(length=255), nullable=True),
    sa.Column('client_timezone', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('date_modified', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('course_log', schema=None) as batch_op:
        batch_op.create_index('course_log_course_index', ['course_id'], unique=False)
        batch_op.create_index('course_log_subject_index', ['subject_id'], unique=False)

    op.create_table('error_log',
    sa.Column('access_log_id', sa.Integer(), nullable=False),
    sa.Column('error_type', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('traceback', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('date_modified', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['access_log_id'], ['access_log.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('error_log', schema=None) as batch_op:
        batch_op.create_index('error_log_access_index', ['access_log_id'], unique=False)

    op.create_table('assignment_log',
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('assignment_version', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('CREATE', 'DELETE', 'EDIT', 'RENAME', 'FORK', 'UNFORK', 'ARCHIVE', 'CORRUPTED', name='assignmentlogevent'), nullable=False),
    sa.Column('field', sa.String(length=255), nullable=True),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('client_timestamp', sa.String(length=255), nullable=True),
    sa.Column('client_timezone', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('date_modified', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignment.id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assignment_log', schema=None) as batch_op:
        batch_op.create_index('assignment_log_assignment_index', ['assignment_id'], unique=False)
        batch_op.create_index('assignment_log_subject_index', ['subject_id'], unique=False)

    op.create_table('role_log',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('authorizer_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('GIVEN', 'REMOVED', 'CHANGED', name='rolelogevent'), nullable=False),
    sa.Column('event_value', sa.String(length=255), nullable=False),
    sa.Column('client_timestamp', sa.String(length=255), nullable=True),
    sa.Column('client_timezone', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('date_modified', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['authorizer_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('role_log', schema=None) as batch_op:
        batch_op.create_index('role_log_authorizer_index', ['authorizer_id'], unique=False)
        batch_op.create_index('role_log_course_index', ['course_id'], unique=False)
        batch_op.create_index('role_log_role_index', ['role_id'], unique=False)
        batch_op.create_index('role_log_subject_index', ['subject_id'], unique=False)

    op.create_table('submission_log',
                    sa.Column('submission_id', sa.Integer(), nullable=False),
                    sa.Column('submission_version', sa.Integer(), nullable=False),
                    sa.Column('assignment_id', sa.Integer(), nullable=False),
                    sa.Column('assignment_version', sa.Integer(), nullable=False),
                    sa.Column('course_id', sa.Integer(), nullable=False),
                    sa.Column('subject_id', sa.Integer(), nullable=False),
                    sa.Column('event_type',
                              sa.Enum('CREATE', 'DELETE', 'EDIT', 'SUBMIT', 'VIEW', 'FEEDBACK', 'COMPILE', 'RUN',
                                      'DEBUG', 'ERROR', 'WARNING', 'INFO', 'COMPLETE', 'TRANSFER', 'CANVAS',
                                      name='submissionlogevent'), nullable=False),
                    sa.Column('file_path', sa.String(length=255), nullable=True),
                    sa.Column('category', sa.String(length=255), nullable=False),
                    sa.Column('label', sa.String(length=255), nullable=False),
                    sa.Column('message', sa.Text(), nullable=False),
                    sa.Column('client_timestamp', sa.String(length=255), nullable=True),
                    sa.Column('client_timezone', sa.String(length=255), nullable=True),
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('date_created', sa.DateTime(), nullable=False),
                    sa.Column('date_modified', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(['assignment_id'], ['assignment.id'], ),
                    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
                    sa.ForeignKeyConstraint(['subject_id'], ['user.id'], ),
                    sa.ForeignKeyConstraint(['submission_id'], ['submission.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )


    with op.batch_alter_table('submission_log', schema=None) as batch_op:
        batch_op.create_index('submission_log_assignment_index', ['assignment_id'], unique=False)
        batch_op.create_index('submission_log_course_index', ['course_id'], unique=False)
        batch_op.create_index('submission_log_subject_index', ['subject_id'], unique=False)
        batch_op.create_index('submission_log_submission_index', ['submission_id'], unique=False)

    op.add_column('assignment', sa.Column('status', sa.Enum('DRAFT', 'PILOT', 'PUBLISHED', 'ARCHIVED', name='assignmentstatus'), nullable=False,
                                  default="DRAFT"))
    op.alter_column('assignment', 'type',
           existing_type=sa.VARCHAR(length=10),
           type_=sa.Enum('READING', 'QUIZ', 'TEXTBOOK', 'MAZE', 'PYTHON', 'JAVA', 'TYPESCRIPT', 'EXPLANATION', name='assignmenttypes'),
           nullable=False)
    op.create_index('assignment_course_index', 'assignment', ['course_id'], unique=False)
    op.create_index('assignment_url_index', 'assignment', ['url'], unique=False)

    with op.batch_alter_table('assignment_group', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.Enum('NONE', 'EXAM', 'HOMEWORK', 'CLASSWORK', 'PROJECT', 'QUIZ', 'LAB', 'READING', name='assignmentgroupcategory'), nullable=False, default="NONE", server_default="NONE"))
        batch_op.create_index('assignment_group_course_index', ['course_id'], unique=False)
        batch_op.create_index('assignment_group_url_index', ['url'], unique=False)

    op.add_column('assignment_group_membership', sa.Column('policy', sa.String(length=255), nullable=True))
    op.create_index('assignment_group_membership_assignment_group_id', 'assignment_group_membership', ['assignment_group_id'], unique=False)
    op.create_index('assignment_group_membership_assignment_id', 'assignment_group_membership', ['assignment_id'], unique=False)
    op.create_index('assignment_group_membership_lookup', 'assignment_group_membership', ['assignment_group_id', 'assignment_id'], unique=False)

    op.add_column('authentication', sa.Column('expires_at', sqlalchemy_utc.sqltypes.UtcDateTime(timezone=True), nullable=True))
    op.add_column('authentication', sa.Column('refresh_token', sa.String(length=255), nullable=True))
    op.alter_column('authentication', 'type',
           existing_type=sa.VARCHAR(length=80),
           default="LOCAL",
           type_=sa.Enum('LOCAL', 'CANVAS', name='authenticationtype'),
           nullable=False)
    op.create_index('authentication_user_index', 'authentication', ['user_id'], unique=False)

    op.add_column('course', sa.Column('kind', sa.Enum('TEMPLATE', 'OFFERING', 'DEFAULT', name='coursekind'), nullable=False, default="TEMPLATE"))
    op.add_column('course', sa.Column('lms_id', sa.Integer(), nullable=True))
    op.alter_column('course', 'service',
           existing_type=sa.VARCHAR(length=80),
           type_=sa.Enum('NATIVE', 'LTI', name='courseservice'),
           default="NATIVE",
           nullable=False)
    op.alter_column('course', 'visibility',
           existing_type=sa.VARCHAR(length=80),
           type_=sa.Enum('PUBLIC', 'PRIVATE', 'STUDENTS', 'ARCHIVED', name='coursevisibility'),
           default="PUBLIC",
           nullable=False)
    op.create_index('course_url_index', 'course', ['url'], unique=False)


    op.add_column('invite', sa.Column('kind', sa.Enum('COURSE_INVITE', 'COURSE_JOIN', name='invitekind'), nullable=False, default="COURSE_INVITE"))
    op.add_column('invite', sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', name='invitestatus'), nullable=False, default="PENDING"))
    op.add_column('invite', sa.Column('approver_id', sa.Integer(), nullable=True))
    op.alter_column('invite', 'role',
           existing_type=sa.VARCHAR(length=80),
           type_=sa.Enum('ADMIN', 'INSTRUCTOR', 'LEARNER', 'TA', 'ADOPTER', 'PROCTOR', 'CONTENT_DEVELOPER', 'NONE', name='userroles'),
           default="LEARNER",
           existing_nullable=True)
    op.create_index('invite_course_id', 'invite', ['course_id'], unique=False)
    op.create_index('invite_user_id', 'invite', ['user_id'], unique=False)
    op.create_index("invite_url_index", 'invite', ['url'], unique=False)
    # TODO: This is not getting generated correctly, need to fix the foreign key
    # op.create_foreign_key('fk_invite_approver_id_user', 'invite', 'user', ['approver_id'], ['id'])


    op.alter_column('report', 'status',
           existing_type=sa.VARCHAR(length=255),
           type_=sa.Enum('QUEUED', 'STARTED', 'FINISHED', 'ERROR', 'EXPIRED', name='reportstatus'),
           default="QUEUED",
           nullable=False)
    op.alter_column('report', 'visibility',
           existing_type=sa.VARCHAR(),
           type_=sa.Enum('PUBLIC', 'PRIVATE', 'STUDENTS', 'ARCHIVED', name='reportvisibility'),
           default="PRIVATE",
           nullable=False)

    op.add_column('review', sa.Column('comment_format', sa.Enum('MARKDOWN', 'HTML', 'TEXT', name='reviewcommentformat'), nullable=False, default="MARKDOWN"))
    op.add_column('review', sa.Column('status', sa.Enum('DRAFT', 'PILOT', 'PUBLISHED', 'PRIVATE', 'DELETED', name='reviewstatus'), nullable=False, default="DRAFT"))
    op.add_column('review', sa.Column('extra_data', sa.Text(), nullable=False))
    op.add_column('review', sa.Column('replaces', sa.Integer(), nullable=True))
    op.add_column('review', sa.Column('tool', sa.String(length=255), nullable=True))
    op.create_index('review_submission_index', 'review', ['submission_id'], unique=False)
    # TODO: This is not getting generated correctly, need to fix the foreign key
    # op.create_foreign_key('fk_review_replaces_id_review', 'review', 'review', ['replaces'], ['id'])
    op.drop_column('review', 'version')

    op.add_column('role', sa.Column('subname', sa.String(length=80), nullable=False))
    op.add_column('role', sa.Column('external_id', sa.Integer(), nullable=True))
    op.alter_column('role', 'name',
           existing_type=sa.VARCHAR(length=80),
           type_=sa.Enum('ADMIN', 'INSTRUCTOR', 'LEARNER', 'TA', 'ADOPTER', 'PROCTOR', 'CONTENT_DEVELOPER', 'NONE', name='userroles'),
           default="LEARNER",
           nullable=False)
    op.create_index('role_course_id', 'role', ['course_id'], unique=False)
    op.create_index('role_user_id', 'role', ['user_id'], unique=False)

    op.add_column('submission', sa.Column('date_started', sqlalchemy_utc.sqltypes.UtcDateTime(timezone=True), nullable=True))
    op.alter_column('submission', 'submission_status',
           existing_type=sa.VARCHAR(length=255),
           type_=sa.Enum('INITIALIZED', 'STARTED', 'IN_PROGRESS', 'SUBMITTED', 'COMPLETED', name='submissionstatuses'),
           default="INITIALIZED",
           nullable=False)
    op.alter_column('submission', 'grading_status',
           existing_type=sa.VARCHAR(length=255),
           type_=sa.Enum('FULLY_GRADED', 'PENDING', 'PENDING_MANUAL', 'FAILED', 'NOT_READY', name='gradingstatuses'),
           default="NOT_READY",
           nullable=False)
    op.drop_index('submission', 'submission_index')
    op.create_index('submission_index', 'submission', ['course_id', 'assignment_id', 'user_id'], unique=False)
    op.create_index('submission_assignment_index', 'submission', ['assignment_id'], unique=False)
    op.create_index('submission_url_index', 'submission', ['url'], unique=False)
    op.create_index('submission_user_index', 'submission', ['user_id'], unique=False)
    # TODO: These two are not getting generated correctly, need to fix the foreign key and unique constraint
    # op.create_unique_constraint(None, 'submission', ['url'])
    # op.create_foreign_key(None, 'submission', 'assignment_group', ['assignment_group_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('user_fs_uniquifier_index', ['fs_uniquifier'], unique=1)
        batch_op.alter_column('date_modified',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('date_created',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('fs_uniquifier',
               existing_type=sa.String(length=64),
               server_default=sa.text('("")'),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('banned',
               existing_type=sa.Boolean(),
               server_default=sa.text('0'),
               type_=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('anonymous',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('proof',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_index('submission_user_index')
        batch_op.drop_index('submission_url_index')
        batch_op.drop_index('submission_assignment_index')
        batch_op.drop_index('submission_index')
        batch_op.create_index('submission_index', ['assignment_id', 'course_id', 'user_id'], unique=False)
        batch_op.alter_column('date_modified',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('date_created',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('version',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('assignment_version',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('course_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('assignment_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('date_locked',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(NULL)'),
               existing_nullable=True)
        batch_op.alter_column('date_due',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(NULL)'),
               existing_nullable=True)
        batch_op.alter_column('date_graded',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(NULL)'),
               existing_nullable=True)
        batch_op.alter_column('date_submitted',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(NULL)'),
               existing_nullable=True)
        batch_op.alter_column('grading_status',
               existing_type=sa.Enum('FULLY_GRADED', 'PENDING', 'PENDING_MANUAL', 'FAILED', 'NOT_READY', name='gradingstatuses'),
               type_=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('submission_status',
               existing_type=sa.Enum('INITIALIZED', 'STARTED', 'IN_PROGRESS', 'SUBMITTED', 'COMPLETED', name='submissionstatuses'),
               type_=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('correct',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('score',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('endpoint',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('url',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('extra_files',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('code',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.drop_column('date_started')

    with op.batch_alter_table('sample_submission', schema=None) as batch_op:
        batch_op.alter_column('date_modified',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('date_created',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('version',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('assignment_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('forked_version',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('feedback',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('inputs',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('output',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('correct',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('score',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('extra_files',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('code',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.drop_index('role_user_id')
        batch_op.drop_index('role_course_id')
        batch_op.alter_column('date_modified',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('date_created',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.Enum('ADMIN', 'INSTRUCTOR', 'LEARNER', 'TA', 'ADOPTER', 'PROCTOR', 'CONTENT_DEVELOPER', 'NONE', name='userroles'),
               type_=sa.VARCHAR(length=80),
               nullable=True)
        batch_op.drop_column('external_id')
        batch_op.drop_column('subname')

    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index('review_submission_index')
        batch_op.alter_column('date_modified',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('date_created',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('submission_version',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('assignment_version',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('author_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('generic',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('location',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('comment',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.drop_column('tool')
        batch_op.drop_column('replaces')
        batch_op.drop_column('extra_data')
        batch_op.drop_column('status')
        batch_op.drop_column('comment_format')

    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.alter_column('date_modified',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('date_created',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('visibility',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('parameters',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('task',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('message',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('progress',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('result',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('attempt',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.Enum('QUEUED', 'STARTED', 'FINISHED', 'ERROR', 'EXPIRED', name='reportstatus'),
               type_=sa.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('invite', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('date_modified',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('date_created',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('role',
               existing_type=sa.Enum('ADMIN', 'INSTRUCTOR', 'LEARNER', 'TA', 'ADOPTER', 'PROCTOR', 'CONTENT_DEVELOPER', 'NONE', name='userroles'),
               type_=sa.VARCHAR(length=80),
               existing_nullable=True)
        batch_op.alter_column('course_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('url',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
        batch_op.drop_column('approver_id')
        batch_op.drop_column('status')
        batch_op.drop_column('kind')

    with op.batch_alter_table('grade_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('explanation', sa.TEXT(), nullable=True))
        batch_op.alter_column('date_modified',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('date_created',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('date_submitted',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('score',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('grader_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_index('course_url')
        batch_op.alter_column('date_modified',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('date_created',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('locked',
               existing_type=sa.Boolean(),
               server_default=sa.text('0'),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('settings',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('term',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('visibility',
               existing_type=sa.Enum('PUBLIC', 'PRIVATE', 'STUDENTS', 'ARCHIVED', name='coursevisibility'),
               type_=sa.VARCHAR(length=80),
               nullable=True)
        batch_op.alter_column('endpoint',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('external_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('service',
               existing_type=sa.Enum('NATIVE', 'LTI', name='courseservice'),
               type_=sa.VARCHAR(length=80),
               nullable=True)
        batch_op.alter_column('owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.drop_column('version')
        batch_op.drop_column('lms_id')
        batch_op.drop_column('kind')

    with op.batch_alter_table('authentication', schema=None) as batch_op:
        batch_op.drop_index('authentication_user_index')
        batch_op.alter_column('date_modified',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('date_created',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('value',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('type',
               existing_type=sa.Enum('LOCAL', 'CANVAS', name='authenticationtype'),
               type_=sa.VARCHAR(length=80),
               nullable=True)
        batch_op.drop_column('refresh_token')
        batch_op.drop_column('expires_at')

    with op.batch_alter_table('assignment_tag', schema=None) as batch_op:
        batch_op.alter_column('date_modified',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('date_created',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('version',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('level',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('kind',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('course_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('assignment_group_membership', schema=None) as batch_op:
        batch_op.drop_constraint('assignment_group_membership_lookup', type_='unique')
        batch_op.drop_index('assignment_group_membership_assignment_id')
        batch_op.drop_index('assignment_group_membership_assignment_group_id')
        batch_op.alter_column('date_modified',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('date_created',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('assignment_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('assignment_group_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('policy')

    with op.batch_alter_table('assignment_group', schema=None) as batch_op:
        batch_op.drop_constraint('url_course_index', type_='unique')
        batch_op.drop_index('assignment_course_index')
        batch_op.alter_column('date_modified',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('date_created',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('version',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('position',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('course_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.drop_column('category')

    with op.batch_alter_table('assignment', schema=None) as batch_op:
        batch_op.drop_constraint('url_course_index', type_='unique')
        batch_op.drop_index('assignment_course_index')
        batch_op.alter_column('date_modified',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('date_created',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('version',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('course_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('extra_starting_files',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('extra_instructor_files',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('starting_code',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('on_eval',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('on_change',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('on_run',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('points',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('ip_ranges',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('subordinate',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('(FALSE)'),
               nullable=True)
        batch_op.alter_column('public',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('(FALSE)'),
               nullable=True)
        batch_op.alter_column('hidden',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('reviewed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('instructions',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('type',
               existing_type=sa.Enum('READING', 'QUIZ', 'TEXTBOOK', 'MAZE', 'PYTHON', 'JAVA', 'TYPESCRIPT', 'EXPLANATION', name='assignmenttypes'),
               type_=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.drop_column('status')

    op.create_table('log',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('date_created', sa.DATETIME(), nullable=True),
    sa.Column('date_modified', sa.DATETIME(), nullable=True),
    sa.Column('assignment_id', sa.INTEGER(), nullable=True),
    sa.Column('assignment_version', sa.INTEGER(), nullable=True),
    sa.Column('course_id', sa.INTEGER(), nullable=True),
    sa.Column('subject_id', sa.INTEGER(), nullable=True),
    sa.Column('file_path', sa.VARCHAR(length=255), nullable=True),
    sa.Column('event_type', sa.VARCHAR(length=255), nullable=True),
    sa.Column('category', sa.VARCHAR(length=255), nullable=True),
    sa.Column('label', sa.VARCHAR(length=255), nullable=True),
    sa.Column('message', sa.TEXT(), nullable=True),
    sa.Column('client_timestamp', sa.VARCHAR(length=255), nullable=True),
    sa.Column('client_timezone', sa.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignment.id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('log', schema=None) as batch_op:
        batch_op.create_index('log_index', ['course_id', 'assignment_id', 'subject_id'], unique=False)

    with op.batch_alter_table('submission_log', schema=None) as batch_op:
        batch_op.drop_index('submission_log_submission_index')
        batch_op.drop_index('submission_log_subject_index')
        batch_op.drop_index('submission_log_course_index')
        batch_op.drop_index('submission_log_assignment_index')

    op.drop_table('submission_log')
    with op.batch_alter_table('role_log', schema=None) as batch_op:
        batch_op.drop_index('role_log_subject_index')
        batch_op.drop_index('role_log_role_index')
        batch_op.drop_index('role_log_course_index')
        batch_op.drop_index('role_log_authorizer_index')

    op.drop_table('role_log')
    with op.batch_alter_table('assignment_log', schema=None) as batch_op:
        batch_op.drop_index('assignment_log_subject_index')
        batch_op.drop_index('assignment_log_assignment_index')

    op.drop_table('assignment_log')
    with op.batch_alter_table('error_log', schema=None) as batch_op:
        batch_op.drop_index('error_log_access_index')

    op.drop_table('error_log')
    with op.batch_alter_table('course_log', schema=None) as batch_op:
        batch_op.drop_index('course_log_subject_index')
        batch_op.drop_index('course_log_course_index')

    op.drop_table('course_log')
    with op.batch_alter_table('access_log', schema=None) as batch_op:
        batch_op.drop_index('access_log_subject_index')

    op.drop_table('access_log')
    # ### end Alembic commands ###
